// server/broadcast-worker/encoder.js
//
// FFmpeg: JPEG frames on stdin at a constant rate → H.264.
// Live-stream settings (YouTube's 1080p30 guidance): High profile, yuv420p,
// constant-ish bitrate capped by maxrate/bufsize, a keyframe every 2s
// exactly (no scene-cut keyframes).
//
// File mode: video only. The container follows the extension: .mp4 is
// written fragmented so the file stays playable even if the process is
// killed mid-game; .ts and .flv are streamable as-is.
//
// YouTube mode: the same video encode plus a silent AAC track (YouTube
// ingest expects audio), sent as FLV over RTMP/RTMPS — nothing on disk.
// The silence is generated by FFmpeg (anullsrc: digital zero), never
// captured from Chromium; it's pulled in step with the video's timestamps
// for as long as video arrives, and -shortest ends it with the video.
const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");

function ffmpegPath() {
  if (process.env.FFMPEG_PATH) return process.env.FFMPEG_PATH;
  try {
    const p = require("ffmpeg-static");
    if (p && fs.existsSync(p)) return p;
  } catch { /* fall through to PATH */ }
  return "ffmpeg";
}

function containerArgs(out, format) {
  // Live FLV: no seeking back to write duration/size at the end.
  if (format === "flv") return ["-f", "flv", "-flvflags", "no_duration_filesize"];
  const ext = path.extname(out).toLowerCase();
  if (ext === ".mp4" || ext === ".mov") return ["-movflags", "+frag_keyframe+empty_moov+default_base_moof", "-f", "mp4"];
  if (ext === ".ts") return ["-f", "mpegts"];
  if (ext === ".flv") return ["-f", "flv"];
  return [];
}

const SILENT_AUDIO = {
  source: "anullsrc=channel_layout=stereo:sample_rate=48000",
  bitrateKbps: 128,
};

function encoderArgs({ mode, fps, width, height, bitrateKbps, threads, out, format }) {
  const gop = Math.round(fps * 2);
  const silentAudio = mode === "youtube";
  return [
    "-hide_banner", "-loglevel", "warning", "-nostats",
    "-progress", "pipe:2", "-stats_period", "5",
    // Input 0: a stream of JPEGs, one per output frame.
    "-f", "image2pipe", "-c:v", "mjpeg", "-framerate", String(fps), "-i", "pipe:0",
    ...(silentAudio
      // Input 1: endless digital silence. Exactly one video + one audio out.
      ? ["-f", "lavfi", "-i", SILENT_AUDIO.source, "-map", "0:v:0", "-map", "1:a:0", "-sn", "-dn"]
      // Video only.
      : ["-an", "-sn", "-dn"]),
    "-vf", `scale=${width}:${height},format=yuv420p`,
    "-c:v", "libx264", "-preset", "veryfast", "-profile:v", "high", "-level:v", "4.1",
    "-b:v", `${bitrateKbps}k`, "-maxrate", `${bitrateKbps}k`, "-bufsize", `${bitrateKbps * 2}k`,
    "-r", String(fps), "-g", String(gop), "-keyint_min", String(gop), "-sc_threshold", "0", "-bf", "2",
    // x264 sizes its thread pool (and memory) to the whole machine by default;
    // a fixed count keeps each stream's footprint predictable on a shared VM.
    ...(threads > 0 ? ["-threads", String(threads)] : []),
    ...(silentAudio
      // -shortest: the silence would never end on its own; stop with the video.
      ? ["-c:a", "aac", "-b:a", `${SILENT_AUDIO.bitrateKbps}k`, "-ar", "48000", "-ac", "2", "-shortest"]
      : []),
    ...containerArgs(out, format),
    "-y", out,
  ];
}

// Returns { proc, write, backlog, progress, finish }.
function startEncoder(cfg, log) {
  if (cfg.mode === "file") fs.mkdirSync(path.dirname(cfg.out), { recursive: true });
  // FFmpeg names its output URL in connection errors; never let the key through.
  const redact = (s) => (cfg.secret ? s.split(cfg.secret).join("<stream key>") : s);
  const bin = ffmpegPath();
  const args = encoderArgs(cfg);
  log(`ffmpeg: ${bin}`);
  // detached: its own process group, so Ctrl+C reaches only the worker,
  // which then ends FFmpeg's input cleanly and lets it finish the file.
  const proc = spawn(bin, args, { stdio: ["pipe", "ignore", "pipe"], detached: true, windowsHide: true });
  proc.stdin.on("error", () => { /* EPIPE once FFmpeg has exited; reported via 'exit' */ });

  const progress = {};
  let buf = "";
  proc.stderr.setEncoding("utf8");
  proc.stderr.on("data", (chunk) => {
    buf += chunk;
    let i;
    while ((i = buf.search(/[\r\n]/)) >= 0) {
      const line = buf.slice(0, i).trim();
      buf = buf.slice(i + 1);
      if (!line) continue;
      const m = /^([a-z0-9_]+)=(.*)$/.exec(line);
      if (m) progress[m[1]] = m[2].trim();
      // MJPEG decodes to full-range yuvj420p; swscale converts it to TV range
      // correctly but warns about the pixel format's name every time.
      else if (!/deprecated pixel format|Last message repeated/.test(line)) log(`ffmpeg: ${redact(line)}`);
    }
  });

  const exited = new Promise((resolve) => proc.on("exit", (code, signal) => resolve({ code, signal })));

  return {
    proc,
    exited,
    progress,
    write: (frame) => { if (proc.stdin.writable) proc.stdin.write(frame); },
    backlog: () => proc.stdin.writableLength,
    // End the input and wait for FFmpeg to flush and close the file/stream.
    async finish(timeoutMs = 20000) {
      if (proc.exitCode == null) proc.stdin.end();
      const t = setTimeout(() => proc.kill("SIGKILL"), timeoutMs);
      const r = await exited;
      clearTimeout(t);
      return r;
    },
  };
}

module.exports = { startEncoder, encoderArgs, ffmpegPath };
